language: c
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:birdfont-team/birdfont -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libglib2.0-dev libgtk-3-dev
         libsqlite3-dev valac libxmlbird-dev libgee-dev 
         libwebkitgtk-3.0-dev libnotify-dev python-doit
script:
  - ./configure
  - doit
